id: P000539
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17609
  title: 藏事要闻（༡༩༤༩-༢༠༡༡）
  author: ''
  volumes:
    72d4ed8acfc24add98f7f31ec72474a1:
      image_group_id: I4PD4239
      title: Volume 1 of 藏事要闻（1949-2011）
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
